### PR TITLE
Add CLI to speech module + enhancements

### PR DESCRIPTION
**Pull request by turicas**
Hi, thanks for your project. I've created a new branch with the following enhancements:

- Use the correct logger object in `audiotools/speech.py`
- Move config-related code (get Wit API key) from `audiotools/speech.py` to `transcriberbot/handlers_messages.py` (needed to add a new bot message in case the API is missing, so the user receive an error feedback instead of empty message)
- Add a command-line interface to `audiotools/speech.py`, making it easy to run the transcribing code without setting up the whole Telegram bot
- Add a space between speeches while iterating over chunks

> Note: because of time constraints, I couldn't test the changes in the file `transcriberbot/handlers_messages.py` (all the other files were tested and the CLI works perfectly).

### CODE REVIEW

**Review by carloalbertobarbano — CHANGES_REQUESTED** [review]
For https://github.com/charslab/TranscriberBot/pull/14/commits/50e579c7de051de141f58c4505ae525eda885618 the whitespaces in lines 84 and 92 are not necessary, as line 100 is applied for every chunk of transcribed text. Line 80 is okay.

**Comment by carloalbertobarbano** [comment]
Thanks a lot for your pull request!

**Comment by turicas** [comment]
> For [50e579c](https://github.com/charslab/TranscriberBot/commit/50e579c7de051de141f58c4505ae525eda885618) the whitespaces in lines 84 and 92 are not necessary, as line 100 is applied for every chunk of transcribed text. Line 80 is okay.

Correct me if I'm wrong, but if I don't add these spaces on lines 84 and 92, the new/updated message will have the last two chunks concatenated without a space (this will be fixed for this pair of chunks when the next chunk is added and the message is updated, but then the last two chunks will be concatenated without a space, until the next loop iteration happens).

**Comment by carloalbertobarbano** [comment]
> > For [50e579c](https://github.com/charslab/TranscriberBot/commit/50e579c7de051de141f58c4505ae525eda885618) the whitespaces in lines 84 and 92 are not necessary, as line 100 is applied for every chunk of transcribed text. Line 80 is okay.
> 
> Correct me if I'm wrong, but if I don't add these spaces on lines 84 and 92, the new/updated message will have the last two chunks concatenated without a space (this will be fixed for this pair of chunks when the next chunk is added and the message is updated, but then the last two chunks will be concatenated without a space, until the next loop iteration happens).

I see now. Yes you are right, during the transcription the last two chunks will be rendered without a whitespace in between.

**Review by carloalbertobarbano — APPROVED** [review]
https://github.com/charslab/TranscriberBot/pull/14/commits/4d952bc3aaa2d40924b3b6e02fc445c2da486c21 Everything seems in order here. I approve moving the wit key loading from the speech package to the bot package and the CLI. Good job

**Review by carloalbertobarbano — APPROVED** [review]
https://github.com/charslab/TranscriberBot/pull/14/commits/50e579c7de051de141f58c4505ae525eda885618 Approved

**Review by carloalbertobarbano — APPROVED** [review]
https://github.com/charslab/TranscriberBot/pull/14/commits/b11835261a26c93bdedca3dcc99a4a558c594028 Approved

**Review by carloalbertobarbano — APPROVED** [review]
https://github.com/charslab/TranscriberBot/pull/14/commits/43be74e2e4b4fdc8824592830c846a585dbb7968 Approved

**Comment by carloalbertobarbano** [comment]
@turicas Thanks for your PR. I merged it into the development branch

**Pull request merged**
